# Location of testing resources: ../data/
# Resources used to test:
# 1. Chlamydia_mapped.txt

#source('../R/percent.R')

test.setUp <-function(){
	Chlamydia<<- read.fasta(file='../data/Chlamydia_mapped.txt')
	res<<-read.csv(file='../data/result.txt')
	resp<<-list()
	for (a in 1:length(res[[1]])){
		resp[[a]]<<-list(position=res[[1]][a], percent=res[[2]][a])
	}
	#Samples are similar to how the pattern are generated by percent.pattern; used for calculation testing
	sample1 <<- list('t1'='a','t2'='a','t3'='a','t4'='c','t5'='c','t6'='t','t7'='g')
	sample2 <<- list('t1'='ag','t2'='at','t3'='ag','t4'='ct','t5'='ca','t6'='ta','t7'='gg')
	sample3 <<- list('t1'='a','t2'='a','t3'='a','t4'='t','t5'='c','t6'='t','t7'='g')
}

test.percent.pattern <- function(){
	test.setUp()
	pattern=percent.pattern(Chlamydia, list(),1)
	for (a in names(pattern)){
		checkEquals(pattern[[a]][1], Chlamydia[[a]][1])
	}
	pattern=percent.pattern(Chlamydia, pattern, 2)
	for (a in names(pattern)){
		checkEquals(pattern[[a]][1], paste(Chlamydia[[a]][1], Chlamydia[[a]][2], sep=''))
	}
	pattern=percent.pattern(Chlamydia, pattern, 3)
	for (a in names(pattern)){
		checkEquals(pattern[[a]][1], paste(Chlamydia[[a]][1], Chlamydia[[a]][2], Chlamydia[[a]][3], sep=''))
	}
}

test.percent.calculate <- function()
{
	test.setUp()
	#Sample 1 expected result:
	#t1:2/3, t2:2/3, t3:2/3, t4:5/6, t5:5/6, t6:1, t7:1
	checkEquals(percent.calculate(sample1, 't1'), 66.66667, tolerance=0.00005)
	checkEquals(percent.calculate(sample1, 't2'), 66.66667, tolerance=0.00005)
	checkEquals(percent.calculate(sample1, 't3'), 66.66667, tolerance=0.00005)
	checkEquals(percent.calculate(sample1, 't4'), 83.33333, tolerance=0.00005)
	checkEquals(percent.calculate(sample1, 't5'), 83.33333, tolerance=0.00005)
	checkEquals(percent.calculate(sample1, 't6'), 100)
	checkEquals(percent.calculate(sample1, 't7'), 100)

	#Sample 2 expected result:
	#t1:5/6 ,t2:1, t3:5/6, t4:1, t5:1, t6:1, t7:1
	checkEquals(percent.calculate(sample2, 't1'), 83.33333, tolerance=0.00005)
	checkEquals(percent.calculate(sample2, 't2'), 100)
	checkEquals(percent.calculate(sample2, 't3'), 83.33333, tolerance=0.00005)
	checkEquals(percent.calculate(sample2, 't4'), 100)
	checkEquals(percent.calculate(sample2, 't5'), 100)
	checkEquals(percent.calculate(sample2, 't6'), 100)
	checkEquals(percent.calculate(sample2, 't7'), 100)

	#Sample 3 expected result: 
	#t1:2/3, t2:2/3, t3:2/3, t4:5/6, t5:1, t6:5/6, t7:1
	checkEquals(percent.calculate(sample3, 't1'), 66.66667, tolerance=0.00005)
	checkEquals(percent.calculate(sample3, 't2'), 66.66667, tolerance=0.00005)
	checkEquals(percent.calculate(sample3, 't3'), 66.66667, tolerance=0.00005)
	checkEquals(percent.calculate(sample3, 't4'), 83.33333, tolerance=0.00005)
	checkEquals(percent.calculate(sample3, 't5'), 100)
	checkEquals(percent.calculate(sample3, 't6'), 83.33333, tolerance=0.00005)
	checkEquals(percent.calculate(sample3, 't7'), 100)
}

 test.similar.percent <- function()
 {
 	test.setUp()
 	result=similar.percent(Chlamydia, 'ASD32')
 	#Return NULL when the reference allele can't be found
 	checkIdentical(result, NULL, "Can't find reference in allelic profiles")
	
 	
 	result=similar.percent(Chlamydia, 'A_D213')
 	checkEquals(resp[[1]], result[[1]])
 }

test.percent.residual <-function()
{
	test.setUp()
	result = percent.residual(Chlamydia, 'A_D213', 2)
	checkIdentical(result, NULL)
	result = percent.residual(Chlamydia, 'A_D213', 1)
	re = strsplit(result, ', ')
	for (a in re[[1]]){
		checkEquals(Chlamydia[[a]][1], Chlamydia[['A_D213']][1])
	}
	
}

test.branch.percent <-function()
{
	test.setUp()
	expected = list('result 1'=list(position=2, percent=100), 'result 2'=list(position=7, percent=100))
	result = branch.percent(chla, 'A_D213', numRes=2)

	checkEquals(expected[['result 1']],result[['result 1']][[1]])
	checkEquals(expected[['result 2']],result[['result 2']][[1]])

}

test.tearDown <- function()
{
  #DEACTIVATED('Deactivating similar test function')
}